personal_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("web_app.urls")),
    path('admin/', admin.site.urls),
]

web_app/urls.py
from django.urls import path
from web_app import views

app_name = "web_app"
urlpatterns = [
    path("", views.index, name = 'index'),
    path("works", views.works, name = 'works'),
    path("about", views.about, name = 'about'),
    path("hireme", views.hireme, name = "hireme")
]

templates/about.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block extrahead %}
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/aboutstyle.css' %}">
    {% endblock %}
</head>


<body>
    <div class="wrapper">

        {% block content %}
        <div class="content" id="content">
            <div class="context">
                <p>
                    Greetings Ladies and Gentlemen!
                    My name is Karthik J., i am from Bangalore, India. I basically belong to a Telugu Family, my father
                    is a retired Army personnel, an Ex-Servicemen, who works for the MES now, and my mother is a Teacher who teach Social, Hindi, English subjects for elementary school.
                    I have completed my undergraduate degree in Mechanical Engineering from Bangalore Institute of Technology, received my graduation on 2023 May!
                    I have been practising Software Engineering for 2 years now, and i have an immense interest and love for coding and Web development!
                    <!-- <a href="https://drive.google.com/file/d/10Vpdpvp_ZSGYKCx4zgcw8SDETdvcA9h-/view?usp=drive_link" target="_blank">click here! -->

                    </a>
                </p>
            </div>
            <!-- <button class="close">X</button> -->
            <!-- <input type="button" class="close" value="X"> -->
        </div>
        {% endblock %}
    </div>

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&family=M+PLUS+1p:wght@100&family=Montserrat:wght@200&family=Oswald:wght@300&display=swap" rel="stylesheet">
    <script  src="{% static 'scripts/basestyle.js' %}"></script>
    <script src="{% static 'script/baselogic.js' %}"></script>
    {% block extrahead %} {% endblock %}
</head>


<body onload="imgslide()">
    <div class="wrapper">
        <nav class="nav-bar" id="nav-bar">
            <div class="brand">

            </div>
            <ul>
                <li class="nav-items" id="thehome">
                    <a href="{% url 'web_app:index' %}">Home</a> 
                </li>
                <li class="nav-items">
                    <a href="{% url 'web_app:works' %}">Works</a> 
                </li>
                <li class="nav-items">
                    <a href="{% url 'web_app:about' %}">About</a> 
                </li>
                <li class="nav-items">
                    <a href="{% url 'web_app:hireme' %}">Hire me!</a> 
                </li>
            </ul>
        </nav>
        <!-- <marquee behavior="scroll" direction="left"><h1>Hope and hustle.!!</h1></marquee> -->
        <div class="myimage">
            <img id="myimage" src="{% static 'images/myimage.png' %}" alt="">
        </div>
        {% block content %}
        {% endblock %}
    </div>

    <link rel="stylesheet" href="{% static 'css/basestyle.css' %}">

</body>
</html>

templates/hireme.html
{% extends 'base.html' %}
{% load static %}

{% block extrahead %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>KarthikJ_Portfolio</title>
<link rel="stylesheet" href="{% static 'css/hiremestyle.css' %}">
{% endblock %}


{% block content %}
    <div class="content" id="content">
        <div class="context">
            <div class="card">
                Please, mention your name and emailId so that i will be notified and revert to you ASAP!
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Send mail!">
                </form>
            </div>
        </div>
        <!-- <button class="close">X</button> -->
        <!-- <input type="button" class="close" value="X"> -->
    </div>
{% endblock %}

templates/work.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block extrahead %}
    <title>Works</title>
    <link rel="stylesheet" href="{% static 'css/workstyle.css' %}">
    {% endblock %}
</head>


<body>
    <div class="wrapper">

        {% block content %}
        <div class="cards">
            <!-- <p class="head1">HTML/ CSS/ JavaScript</p> -->
            <div class="main-card">
                <div class="image">
                    <img src="{% static 'images/loginproj.png' %}" alt="">
                    <div class="contents">
                        <p>A basic registration form with subtle styling!</p>
                        <p>A basic registraion form, with subtle styling added with some basic error validations and error notifications!.</p>
                        <button><a href="https://github.com/Karthik150502/LogIn_Page" target="_blank">Source</a></button>
                        <button><a href="https://warm-vacherin-4ff7cf.netlify.app/" target="_blank">Demo</a></button>
                    </div>
                </div>
            </div>

            <div class="main-card">
                <div class="image">
                    <img src="{% static 'images/bouncing_ball.png' %}" alt="">
                    <div class="contents">
                        <p>An animated bouncing ball!</p>
                        <p>An animated bouncing ball, with some smart detailing, done only using HTML and CSS!</p>
                        <button><a href="https://github.com/Karthik150502/Animated-Ball" target="_blank">Source</a></button>
                        <button><a href="https://serene-frangollo-5dc749.netlify.app/" target="_blank">Demo</a></button>
                    </div>
                </div>
        
            </div>

            <div class="main-card">
                <div class="image">
                    <img src="{% static 'images/loading_animation2.png' %}" alt="">
                    <div class="contents">
                        <p>A smooth loading animation!</p>
                        <p>A aesthetic loading animation, with an aesthetic font! Only done usinh HTML and CSS.</p>
                        <button><a href="https://github.com/Karthik150502/LoadingAnimaion2" target="_blank">Source</a></button>
                        <button><a href="https://golden-liger-47e74b.netlify.app/" target="_blank">Demo</a></button>
                    </div>
                </div>
        
            </div>
            <div class="main-card">
                <div class="image">
                    <img src="{% static 'images/periodic_table.png' %}" alt="">
                    <div class="contents">
                        <p>Periodic Table!</p>
                        <p>The periodic table, with all its elements, and some hidden surprise animations, hover through some elements to know!</p>
                        <button><a href="https://github.com/Karthik150502/Periodic_Table" target="_blank">Source</a></button>
                        <button><a href="https://tubular-madeleine-d58785.netlify.app/" target="_blank">Demo</a></button>
                    </div>
                </div>
        
            </div>

            <div class="main-card">
                <div class="image">
                    <img src="{% static 'images/glowing_text.png' %}" alt="">
                    <div class="contents">
                        <p>Glowing text!</p>
                        <p>A text that glows like a LED bulb, but also blinks infinitely with some great fonts! Some fun with HTML and CSS.</p>
                        <button><a href="https://github.com/Karthik150502/text_Glow" target="_blank">Source</a></button>
                        <button><a href="https://snazzy-queijadas-c2c6df.netlify.app/" target="_blank">Demo</a></button>
                    </div>
                </div>
        
            </div>

            <div class="main-card">
                <div class="image">
                    <img src="{% static 'images/basic_calculator.png' %}" alt="">
                    <div class="contents">
                        <p>A basic Calculator!</p>
                        <p>Basic calculator for some small mathematical calculations, with modulous operator also!</p>
                        <button><a href="https://github.com/Karthik150502/Basic_Calculator" target="_blank">Source</a></button>
                        <button><a href="https://melodic-llama-c8421f.netlify.app/" target="_blank">Demo</a></button>
                    </div>
                </div>
        
            </div>
        </div>


        {% endblock %}
    </div>

</body>
</html>